[brightness]
enable_ddcutil = true
minimum_brightness = 0.14999999664723873

[location]
address = "Clermont Ferrand, France"

[nightlight]
enabled = false

[plugins]
# enabled = [ "yuuto/arch-updater", "noctalia/wallhaven" ]
enabled = [ "noctalia/wallhaven" ]

[plugin_settings."noctalia/wallhaven"]
download_dir = "/home/strawberries/Pictures/NoctaliaWallpapers"

[wallpaper]
directory = "/home/strawberries/Pictures/Wallpapers"

[system.monitor]
cpu_temp_activity_threshold = 70
