[bar.default]
background_opacity = 1.0
radius = 20
radius_top_left = 0
radius_top_right = 0

[desktop_widgets.grid]
visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
    background = true
    background_opacity = 1.0
    background_radius = 20
    shadow = false

    [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
    background_opacity = 1.0
    background_radius = 20

    [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
    background = true
    background_opacity = 1.0
    bloom_intensity = 0.0
    inner_diameter = 0.60000000000000009
    primary_color = "surface"
    secondary_color = "primary"
    wave_thickness = 1.0

[hooks]
# Intentionnaly empty because this theme doesn't need wallpaper color processing
wallpaper_changed = ""

[notification]
background_opacity = 1.0

[osd]
background_opacity = 1.0

[shell.panel]
transparency_mode = "solid"

[shell.screen_corners]
size = 20

[shell.shadow]
alpha = 0.39999999105930328

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Pink"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kitty", "qt" ]
    community_ids = [ "spicetify", "pywalfox-beta4", "discord", "prismlauncher", "steam", "obs" ]

[wallpaper]
edge_smoothness = 0.0
transition = [ "zoom" ]
transition_on_startup = true

[widget.media]
art_size = 20

[widget.workspaces]
active_pill_size = 1.75
empty_color = "outline"
occupied_color = "surface_variant"
scale = 1.1500000000000001
