$SCRIPT = ~/.config/HyprV/waybar/scripts

bind = , xf86audioraisevolume, exec, $SCRIPT/volume --inc 
bind = , xf86audiolowervolume, exec, $SCRIPT/volume --dec 
bind = , xf86AudioMicMute, exec, $SCRIPT/volume --toggle-mic 
bind = , xf86audioMute, exec, $SCRIPT/volume --toggle 

bind = , xf86KbdBrightnessDown, exec, $SCRIPT/kb-brightness --dec 
bind = , xf86KbdBrightnessUp, exec, $SCRIPT/kb-brightness --inc 

bind = , xf86MonBrightnessDown, exec, $SCRIPT/brightness --dec 
bind = , xf86MonBrightnessUp, exec, $SCRIPT/brightness --inc 

bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 
bind = , XF86AudioMicMute, exec, pamixer --default-source -m
bind = , XF86AudioMute, exec, pamixer -t
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

bind = , keyboard_brightness_up_shortcut, exec, brightnessctl -d *::kbd_backlight set +33%
bind = , keyboard_brightness_down_shortcut, exec, brightnessctl -d *::kbd_backlight set 33%-

bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
