[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer", "discord-rpc" ]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.discord-rpc]
command = "discord-rpc-lsp"

[language-server.rust-analyzer.config]
cargo.buildScripts.enable = true
procMacro.enable = true
diagnostics.enable = true

[[language]]
name = "json"
auto-format = true
formatter = { command = "jq", args = ["."] }
