[bar.default]
background_opacity = 1.0
center = [ "temp", "ram" ]
end = [
    "media",
    "spacer_1",
    "widget",
    "notifications",
    "volume",
    "brightness",
    "bluetooth",
    "network",
    "battery",
    "spacer_1",
    "clock"
]
margin_ends = 0
margin_opposite_edge = 5
radius = 20
radius_top_left = 0
radius_top_right = 0
start = [ "launcher", "spacer_1", "workspaces", "spacer_1", "tray" ]

[brightness]
enable_ddcutil = true
minimum_brightness = 0.14999999664723873

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 192.0
    box_width = 400.0
    cx = 1280.0
    cy = 720.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = true
        background_opacity = 1.0
        background_radius = 20
        center_text = true
        clock_style = "digital"
        shadow = false

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 912.0
    output = "DP-1"
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background_opacity = 1.0
        background_radius = 20

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1200.0
    output = "DP-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = true
        background_opacity = 1.0
        bloom_intensity = 0.0
        inner_diameter = 0.60000000000000009
        primary_color = "surface"
        rotation_speed = 0.0
        secondary_color = "primary"
        sensitivity = 1.5
        visualization_mode = "wave"
        wave_thickness = 1.0

[hooks]
# Explicitly empty the hook so the wallpaper-changed script does not trigger in this theme
wallpaper_changed = ""

[keybinds]
down = [ "Down", "Ctrl+n", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+p", "Ctrl+k" ]

[location]
address = "Clermont Ferrand, France"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
offset_x = 8

[osd]
offset_x = 8
orientation = "vertical"
position_vertical = "top_left"

[nightlight]
enabled = true

[plugins]
enabled = [ "yuuto/arch-updater" ]

[shell]
clipboard_enabled = false
panel_anchor_bar = "default"
password_style = "random"
screen_time_enabled = true

    [shell.launcher]
    fetch_exchange_rates = false

    [shell.mpris]
    blacklist = [ "Mozilla firefox" ]

    [shell.panel]
    launcher_placement = "attached"
    open_near_click_control_center = true
    transparency_mode = "solid"

    [shell.screen_corners]
    enabled = true
    size = 20

    [shell.shadow]
    alpha = 0.39999999105930328

[system.monitor]
cpu_temp_activity_threshold = 70

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Pink"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kitty", "qt" ]
    community_ids = [ "spicetify", "pywalfox-beta4", "discord", "prismlauncher", "steam", "obs" ]

[wallpaper]
edge_smoothness = 0.0
transition = [ "zoom" ]
transition_on_startup = true

    # [wallpaper.default]
    # path = "/home/strawberries/Pictures/Wallpapers/nix/nix-wallpaper-nineish-catppuccin-mocha.png"
    #
    # [wallpaper.last]
    # path = "/home/strawberries/Pictures/Wallpapers/nix/nix-wallpaper-nineish-catppuccin-mocha.png"
    #
    # [wallpaper.monitors.DP-1]
    # path = "/home/strawberries/Pictures/Wallpapers/nix/nix-wallpaper-nineish-catppuccin-mocha.png"
    #
    # [wallpaper.monitors.HDMI-A-2]
    # path = "/home/strawberries/Pictures/Wallpapers/nix/nix-wallpaper-nineish-catppuccin-mocha.png"

[widget.clock]
format = "{:%a %D %H:%M:%S}"

[widget.media]
art_size = 20
hide_when_no_media = true
max_length = 250
title_scroll = "on_hover"

    [widget.media.actions]
    back = "none"
    forward = "none"
    scroll_down = "none"
    scroll_up = "none"

[widget.network]
show_label = false

[widget.ram]
custom_image = "a"

[widget.spacer_1]
length = 18
type = "spacer"

[widget.temp]
display = "text"
glyph = "temperature"

[widget.widget]
type = "yuuto/arch-updater:widget"

[widget.workspaces]
active_pill_size = 1.75
empty_color = "outline"
occupied_color = "surface_variant"
scale = 1.1500000000000001
